mean: [0.7066, 0.4772, 0.6672]
std: [0.1677, 0.1839, 0.1412]
network_image_size: 224
batch_size: 16
epochs: 1
learning_rate: 0.01
test_every: 5
num_classes: 4
devices: [0]
model_name: resnet38
# paths: #colab
#   train: "/content/drive/MyDrive/sub/train"
#   valid: "/content/drive/MyDrive/sub/valid"
#   test: "/content/drive/MyDrive/sub/train"
#   mask_valid: "/content/oeem/data/BCSS-WSSS/sub/valid/mask"
#   weights: "classification/weights"
#   results: "classification/result"
#   resnet38: "/content/drive/MyDrive/wider_resnet38.pth.tar"
#   valid_result: "classification/valid_result"

paths: 
  train: "/Users/thachha/Desktop/AIO2025-official/AIMA/CP- WSSS/PBIP/data/BCSS-WSSS/sub/train"
  valid: "/Users/thachha/Desktop/AIO2025-official/AIMA/CP- WSSS/PBIP/data/BCSS-WSSS/sub/valid/img"
  test: "/Users/thachha/Desktop/AIO2025-official/AIMA/CP- WSSS/PBIP/data/BCSS-WSSS/sub/test"
  mask_valid: "/Users/thachha/Desktop/AIO2025-official/AIMA/CP- WSSS/PBIP/data/BCSS-WSSS/sub/valid/mask"
  weights: "classification/weights"
  results: "classification/result"
  resnet38: "classification/weights/res38d.pth.tar"
  valid_result: "classification/valid_result"
